project:
  type: website
  output-dir: docs

website:
  title: "China Pharma R user group meeting 2024"
  description: ""
  site-url: https://pharmarug.github.io/pharmarug-2024/
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: reg.qmd
        text: Registration
        icon: "calendar"
      - href: program.qmd
        text: Program
        icon: "folder"
  page-footer:
    left: |
      Supported by
      [![](resources/rconsortium.png){fig-alt="Posit" width=120px}](https://www.r-consortium.org/)
    center:
      - text: "Good software engineering practice for R packages"
        href: https://openpharma.github.io/workshop-r-swe/
      - text: "PharmaRUG 2023"
        href: https://pharmarug.github.io/pharmarug-2023/
      - text: "Open Source Clinical Reporting summeR"
        href: https://insightsengineering.github.io/nest-2023-summeR/
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    mainfont: system-ui
    fontcolor: "#161b58"
    css: styles.css
    toc: false

editor: source
